[build-system]
requires = ["setuptools >= 61.0"]  # Specify the minimum version of setuptools
build-backend = "setuptools.build_meta"

[project]
name = "myawesomepackage"
version = "0.1"
description = "My first Python package"
requires-python = ">=3.8"